name: canoe-backend
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - matplotlib
    - pandas
    - numpy
    - xmltodict
    - openpyxl
    - requests
    - pyyaml
    - xlsxwriter
    - scipy
    - tsam # WARNING: this is for representative period selection and requires modification. See README in representative_periods
    - pip
    - pip:
        - canoe_schema @ git+ssh://git@github.com/CANOE-main/canoe-schema.git@yep/v4